services:
  - type: web
    name: multiplayer-arena-cpp
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: ""
